name: Build and deploy Node.js app to Azure Web App - teachmeremsey

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'teachmeremsey'  # Centralized environment variable for the web app name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'  # Adds caching for npm dependencies

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Copy static files  # Copy static files for Next.js or static assets
        run: |
          cp -R ./public ./.next/standalone/public
          cp -R ./.next/static ./.next/standalone/.next/static

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./.next/standalone  # Directly upload the standalone directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./downloaded_artifact  # Specify a directory to download the artifact into

      - name: Login to Azure  # Using publish-profile instead of client-id, tenant-id, and subscription-id
        uses: azure/login@v2
        with:
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          package: ./downloaded_artifact  # Deploy from the directory where the artifact was downloaded
